### ISSUE TITLE
Private Datasets

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-web-ui#172]
## About
Datasets on the platform can be made public or private. Access permissions are enforced centrally.

## Product Requirements
**Platform Backend (https://github.com/kamu-data/kamu-cli/issues/676)**:

- [x] Store public/private status in DB
- [x] Enforce permissions during read/write operations
  - [x] Ensure private datasets do not appear in search results
  - [x] Figure out how derivative datasets will react to dependencies becoming private
  - [x] Check permissions in smart/simple transfer protocols
  - [x] `DependencyGraph` should store all deps but ensure to filter inaccessible items
- [x] Referring to a private dataset when you don't have permissions should react as if dataset does not exist

**Platform Frontend**:
- [x] https://github.com/kamu-data/kamu-web-ui/issues/411
- [x] https://github.com/kamu-data/kamu-web-ui/issues/506 
  - Display public / private status and icons 
- [x] https://github.com/kamu-data/kamu-web-ui/issues/412
- [x] Navigating to URL of private datasets should return 404
- [ ] Sharing between accounts is out-of-scope
  - Mockup account permissions in dataset settings

## Technical Details

- RFC: [link](https://docs.google.com/document/d/1bycQpRD015YyKNZD1atRScC2uChVWStAE70UsdZjX0g)

## Test plan

Described in:
- https://github.com/kamu-data/kamu-testing/pull/2

**Comment by sergiimk** [comment]
# Acceptance testing results

## 1. Possible bug in derivative dataset input accessibility check
STR:
1. login as your user (in my case `sergiimk`)
2. create a private root dataset `priv-test`
3. use file upload to add any data (I used an `ndjson` file)
4. switch visibility to `public`
5. logout
6. login as `alice`
7. create derivative dataset
8. click `Add Transformation`
9. lookup `test-root` and select the previously created dataset (I was able to see the now public `sergiimk/priv-test`)
10. specify Datafusion engine and use `select * from 'priv-test'` as query
11. click `Save`
12. Observe error:
```
Error:
Invalid event: Some input dataset(s) are inaccessible: 'priv-test': SetTransform(SetTransform { inputs: [TransformInput { dataset_ref: ID(DatasetID<Ed25519Pub>(fed01ecb302e222ab99a88f731a77093bda13d3309c444b383c92082b560b8181e09b)), alias: Some("priv-test") }], transform: Sql(TransformSql { engine: "datafusion", version: None, query: None, queries: Some([SqlQueryStep { alias: None, query: "select * from 'priv-test'" }]), temporal_tables: None }) })
``` 
The public dataset is claimed to be inaccessible when committing `SetTransform`, but `alice` can open and view data.

![Image](https://github.com/user-attachments/assets/3259a986-b235-4f01-b660-15f75689e66f)

Same happens even when the dataset is initially created as `public` and all the existing datasets, so it's currently not possible to create a derivative dataset on the platofrm.

## 2. Typo
When changing visibility to `private` the platform message reads:
`"It will appear in search results on for people with access"`
should be: `only for people`

![Image](https://github.com/user-attachments/assets/12231cd9-a760-408a-8665-4ce744ba1f06)

## 3. Contrib datasets CI action
CI action for updating example datasets [seems to be failing](https://github.com/kamu-data/kamu-contrib/actions/runs/13062290123/job/36447848182) since the release of privacy changes suggesting a possible regression.

**Comment by sergiimk** [comment]
# Acceptance testing results (round 2)

## 1. Derivative update re-scheduling issue
1. User A: creates public root dataset
2. User A: adds some data to it
3. User B: created derivative dataset based on previous
4. User B: configures automatic updates (1 min batching, 1 min records to await)
5. Observe: new flow created and derivative dataset updated successfully
6. User A: changes visibility to private
7. User A: adds more data to the dataset
8. User B: tries to update dataset manually
9. Observe: flow is not scheduled
10. User A: changes visibility back to public
11. User B: go to automatic update settings and re-save the flow config
12. Observe: flow is scheduled, but:
  a. after one minute passes the flow still doesn't trigger and is stuck in this state
  b. even if User A adds more data to the root dataset - derivative is not getting updates - the system seems stuck

![Image](https://github.com/user-attachments/assets/2c1b1b69-ec03-4065-94d1-d28ccde67bed)

When I try to disable the scheduled updates for derivative dataset the Save button becomes inactive not allowing me to do so:

![Image](https://github.com/user-attachments/assets/012f6d35-552c-4ab9-b3d3-ad95626bf245)

Thus I'm stuck in unrecoverable state with the only option to delete the derivative dataset and start from scratch.

**Comment by sergiimk** [comment]
# Acceptance testing (round 3)
* Didn't find any issues except from the one mentioned above from round 2 of testing - it's important but not a blocker for the epic
* Made a suggestion to add `--visibility public` to the Jupyter COVID tutorial to ensure people push datasets as public
* Left several questions about the deployment procedure in Slack after clarifying which we should be ready to propagate this to `demo` environment

**Comment by s373r** [comment]
> # Acceptance testing results (round 2)
> ## 1. Derivative update re-scheduling issue
> 
> ...
>
> 7. User A: adds more data to the dataset
> 
> 8. User B: tries to update dataset manually
> 
> 9. Observe: flow is not scheduled
> 
> 10. User A: changes visibility back to public
> 
> 11. User B: go to automatic update settings and re-save the flow config
> 
> 12. Observe: flow is scheduled, but:
>   a. after one minute passes the flow still doesn't trigger and is stuck in this state
>   b. even if User A adds more data to the root dataset - derivative is not getting updates - the system seems stuck

I double-checked locally and on europort, after User B clicks on the manual update of the derivative dataset, the update is successful (if the root dataset is accessible).

<details>
  <summary>`s373r/test` deriv dataset (screenshot)</summary>
  
https://platform.europort.kamu.dev/s373r/test?tab=flows

![Image](https://github.com/user-attachments/assets/b0dbc142-64b5-4e43-a3df-e23ef5fea8b2)
</details>

If the root dataset NOT is accessible & pts. 8-9 are about notification, then yes, that is correct and expected behavior.

<details>
  <summary>Error notification (screenshot)</summary>
  
![Image](https://github.com/user-attachments/assets/226066b0-a407-4fd1-9d58-1ac7e0d8226d)
</details>

---

>     12. Observe: flow is scheduled, but:
>         a. after one minute passes the flow still doesn't trigger and is stuck in this state
>         b. even if User A adds more data to the root dataset - derivative is not getting updates - the system seems stuck

Speaking of this pt, two separate tasks were created:
- https://github.com/kamu-data/kamu-web-ui/issues/550
  - To revise this menu and make it more transparent/clear to the user (not to create false expectations)
- https://github.com/kamu-data/kamu-cli/issues/1070
  - `b. even if User A adds more data to the root dataset (c)` it couldn't have led to anything -- to change this, this task was added

**Comment by s373r** [comment]
> # Acceptance testing (round 3)
> 
> - R3.1) Didn't find any issues except from the one mentioned above from round 2 of testing - it's important but not a blocker for the epic
> 
> - R3.2) Made a suggestion to add `--visibility public` to the Jupyter COVID tutorial to ensure people push datasets as public
> 
> - R3.3) Left several questions about the deployment procedure in Slack after clarifying which we should be ready to propagate this to `demo` environment

✅ R3.1 [investigated (comment above)](https://github.com/kamu-data/kamu-web-ui/issues/172#issuecomment-2650898013)

✅ R3.2:
- https://github.com/kamu-data/kamu-cli/pull/1060 (changes)
- https://github.com/kamu-data/kamu-cli/pkgs/container/kamu-cli-demo-jupyter/351483151?tag=0.17.1 (image built & deployed to `europort` env)

✅ R3.3: instructions provided.

---

Thus, I propose to move on to the procedure of deploying on the Demo environment -- as soon as it is approved, I can deploy it.

@sergiimk, any questions/comments/suggestions?

CC @zaychenko-sergei

**Comment by sergiimk** [comment]
Acceptance testing passed and the feature was rolled out to `demo` env - closing! 🚀 👍 🎉
